import {FrameDefault} from "@/pageFrame";
import styled from "@emotion/styled";
import Head from "next/head";
import {useRouter} from "next/navigation";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>QR AXISJ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FrameDefault>
        <Div>
          <h1>Hello AXISJ</h1>
        </Div>
      </FrameDefault>
    </>
  );
}

const Div = styled.div`
  padding: 20px;
`;
