import {FrameDefault} from "@/pageFrame";
import {SMixinFlexColumn} from "@/styles";
import styled from "@emotion/styled";
import {QRCode} from "antd";
import Head from "next/head";
import {useParams} from "next/navigation";


export default function Home() {
  const params = useParams();

  if(!params?.text) return null;

  return (
    <>
      <Head>
        <title>QR AXISJ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FrameDefault>
        <Div>
          <h1>Google Authenticator</h1>
          <QRCode value={`${params?.text ?? "-"}`} size={300}/>

          <br/>

          <h3>안드로이드 버전</h3>
          <ul>
            <li>[Google OTP] 검색 및 다운로드</li>
            <li>시작 클릭 및 계정 추가</li>
            <li>바코드 스캔 선택 후 이메일 내용 QR코드 스캔</li>
            <li>인트라넷 비밀번호 아래 OTP 코드에 생성된 6자리코드 입력 후 로그인</li>
          </ul>
          <h3>iOS 버전</h3>
          <ul>
            <li>[Google Authenticator] 검색 및 다운로드</li>
            <li>시작 클릭 및 계정 추가</li>
            <li>바코드 스캔 선택 후 이메일 내용 QR코드 스캔</li>
            <li>인트라넷 비밀번호 아래 OTP 코드에 생성된 6자리코드 입력 후 로그인</li>
          </ul>
        </Div>
      </FrameDefault>
    </>
  );
}

const Div = styled.div`
    padding: 20px;
    ${SMixinFlexColumn("flex-start", "center")};

    h3 {
        margin-bottom: 0;
    }
    .ant-qrcode {
        flex: none;
    }
`;
